### ISSUE TITLE
Last week's broken front end 

### ISSUE THREAD

**Issue by sihrus** [junzhiwang/Askme#40] opened 2017-10-29 16:44 UTC
Just putting this issue here for documentation purposes. It appears to be fixed. Steven could maybe give a line or two of what happened.

**Comment by junzhiwang** [comment] 2017-10-31 16:14
It had been fixed, was caused by just a period of backend maintenance, close it because it's not a front end issue.

**Closed by junzhiwang** 2017-10-31 16:14 UTC
